# ##################################################################################################### #
#                                                                                                       #
#                                                  DML                                                  #
#                                                                                                       #
# ##################################################################################################### #
USE EC3_CC1M;
#####################################################
# | INSERT | UPDATE | DELETE | [TABELA CLIENTES]
#####################################################

INSERT INTO CLIENTES (CODIGO_CLIENTE, CNPJ_CLIENTE, RAZAO_SOCIAL_CLIENTE, RAMO_ATIVIDADE_CLIENTE, DATA_CADASTRAMENTO_CLIENTE)
VALUES (1, '12.345.678/0001-01', 'Empresa Azeite Verde', 'Alimentício', '2023-01-15');
INSERT INTO CLIENTES (CODIGO_CLIENTE, CNPJ_CLIENTE, RAZAO_SOCIAL_CLIENTE, RAMO_ATIVIDADE_CLIENTE, DATA_CADASTRAMENTO_CLIENTE)
VALUES (2, '98.765.432/0001-09', 'Indústria de Tecidos Raros', 'Têxtil', '2023-02-20');
INSERT INTO CLIENTES (CODIGO_CLIENTE, CNPJ_CLIENTE, RAZAO_SOCIAL_CLIENTE, RAMO_ATIVIDADE_CLIENTE, DATA_CADASTRAMENTO_CLIENTE)
VALUES (3, '11.222.333/0001-44', 'Construtora Paredes Fortes', 'Construção Civil', '2023-03-05');
INSERT INTO CLIENTES (CODIGO_CLIENTE, CNPJ_CLIENTE, RAZAO_SOCIAL_CLIENTE, RAMO_ATIVIDADE_CLIENTE, DATA_CADASTRAMENTO_CLIENTE)
VALUES (4, '22.333.444/0001-55', 'Fábrica de Móveis Exóticos', 'Mobiliário', '2023-04-10');
INSERT INTO CLIENTES (CODIGO_CLIENTE, CNPJ_CLIENTE, RAZAO_SOCIAL_CLIENTE, RAMO_ATIVIDADE_CLIENTE, DATA_CADASTRAMENTO_CLIENTE)
VALUES (5, '33.444.555/0001-66', 'Tecnologia Avançada Ltda.', 'Tecnologia', '2023-05-25');

UPDATE CLIENTES 
SET RAZAO_SOCIAL_CLIENTE = 'Empresa Azeite Verde Ltda.' 
WHERE CODIGO_CLIENTE = 1;
UPDATE CLIENTES 
SET RAMO_ATIVIDADE_CLIENTE = 'Tecnologia e Inovação' 
WHERE CODIGO_CLIENTE = 5;

DELETE FROM CLIENTES 
WHERE CODIGO_CLIENTE = 5;
INSERT INTO CLIENTES (CODIGO_CLIENTE, CNPJ_CLIENTE, RAZAO_SOCIAL_CLIENTE, RAMO_ATIVIDADE_CLIENTE, DATA_CADASTRAMENTO_CLIENTE)
VALUES (5, '33.444.555/0001-66', 'Tecnologia Avançada Ltda.', 'Tecnologia', '2023-05-25');

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA FORNECEDORES]
#####################################################

INSERT INTO FORNECEDORES (CODIGO_FORNECEDOR, CNPJ_FORNECEDOR, RAZAO_SOCIAL_FORNECEDOR)
VALUES (1, '55.666.777/0001-88', 'Fornecedor de Peças Únicas');
INSERT INTO FORNECEDORES (CODIGO_FORNECEDOR, CNPJ_FORNECEDOR, RAZAO_SOCIAL_FORNECEDOR)
VALUES (2, '77.888.999/0001-99', 'Distribuidora de Materiais Especiais');
INSERT INTO FORNECEDORES (CODIGO_FORNECEDOR, CNPJ_FORNECEDOR, RAZAO_SOCIAL_FORNECEDOR)
VALUES (3, '88.999.111/0001-22', 'Importadora de Produtos Exóticos');
INSERT INTO FORNECEDORES (CODIGO_FORNECEDOR, CNPJ_FORNECEDOR, RAZAO_SOCIAL_FORNECEDOR)
VALUES (4, '99.111.222/0001-33', 'Exportadora de Metais Preciosos');
INSERT INTO FORNECEDORES (CODIGO_FORNECEDOR, CNPJ_FORNECEDOR, RAZAO_SOCIAL_FORNECEDOR)
VALUES (5, '11.222.333/0001-44', 'Fábrica de Equipamentos Industriais');

UPDATE FORNECEDORES 
SET RAZAO_SOCIAL_FORNECEDOR = 'Fornecedor de Peças Únicas Ltda.' 
WHERE CODIGO_FORNECEDOR = 1;
UPDATE FORNECEDORES 
SET CNPJ_FORNECEDOR = '55.666.777/0002-99' 
WHERE CODIGO_FORNECEDOR = 2;

DELETE FROM FORNECEDORES 
WHERE CODIGO_FORNECEDOR = 5;
INSERT INTO FORNECEDORES (CODIGO_FORNECEDOR, CNPJ_FORNECEDOR, RAZAO_SOCIAL_FORNECEDOR)
VALUES (5, '11.222.333/0001-44', 'Fábrica de Equipamentos Industriais');

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA TIPOS_ENDERECO]
#####################################################

INSERT INTO TIPOS_ENDERECO (CODIGO_TIPO_ENDERECO, NOME_TIPO_ENDERECO)
VALUES (1, 'Residencial');
INSERT INTO TIPOS_ENDERECO (CODIGO_TIPO_ENDERECO, NOME_TIPO_ENDERECO)
VALUES (2, 'Comercial');
INSERT INTO TIPOS_ENDERECO (CODIGO_TIPO_ENDERECO, NOME_TIPO_ENDERECO)
VALUES (3, 'Industrial');
INSERT INTO TIPOS_ENDERECO (CODIGO_TIPO_ENDERECO, NOME_TIPO_ENDERECO)
VALUES (4, 'Rural');
INSERT INTO TIPOS_ENDERECO (CODIGO_TIPO_ENDERECO, NOME_TIPO_ENDERECO)
VALUES (5, 'Corporativo');

UPDATE TIPOS_ENDERECO 
SET NOME_TIPO_ENDERECO = 'Residencial Urbano' 
WHERE CODIGO_TIPO_ENDERECO = 1;
UPDATE TIPOS_ENDERECO 
SET NOME_TIPO_ENDERECO = 'Comercial Urbano' 
WHERE CODIGO_TIPO_ENDERECO = 2;

DELETE FROM TIPOS_ENDERECO WHERE CODIGO_TIPO_ENDERECO = 5;
INSERT INTO TIPOS_ENDERECO (CODIGO_TIPO_ENDERECO, NOME_TIPO_ENDERECO) VALUES (5, 'Corporativo');

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA QUALIFICACOES]
#####################################################

INSERT INTO QUALIFICACOES (CODIGO_QUALIFICACAO, NOME_QUALIFICACAO)
VALUES (1, 'Engenharia Mecânica');
INSERT INTO QUALIFICACOES (CODIGO_QUALIFICACAO, NOME_QUALIFICACAO)
VALUES (2, 'Ciências da Computação');
INSERT INTO QUALIFICACOES (CODIGO_QUALIFICACAO, NOME_QUALIFICACAO)
VALUES (3, 'Administração de Empresas');
INSERT INTO QUALIFICACOES (CODIGO_QUALIFICACAO, NOME_QUALIFICACAO)
VALUES (4, 'Design Gráfico');
INSERT INTO QUALIFICACOES (CODIGO_QUALIFICACAO, NOME_QUALIFICACAO)
VALUES (5, 'Biotecnologia');

UPDATE QUALIFICACOES 
SET NOME_QUALIFICACAO = 'Engenharia Mecatrônica' 
WHERE CODIGO_QUALIFICACAO = 1;
UPDATE QUALIFICACOES 
SET NOME_QUALIFICACAO = 'Administração Pública' 
WHERE CODIGO_QUALIFICACAO = 3;

DELETE FROM QUALIFICACOES 
WHERE CODIGO_QUALIFICACAO = 5;
INSERT INTO QUALIFICACOES (CODIGO_QUALIFICACAO, NOME_QUALIFICACAO)
VALUES (5, 'Biotecnologia');

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA PESSOAS_CONTATO]
#####################################################

INSERT INTO PESSOAS_CONTATO(CODIGO_PESSOA_CONTATO,NOME_PESSOA_CONTATO ,CPF_PESSOA_CONTATO)  
VALUES(1,'Joaquim Alvarenga','12345678900');  
INSERT INTO PESSOAS_CONTATO(CODIGO_PESSOA_CONTATO,NOME_PESSOA_CONTATO ,CPF_PESSOA_CONTATO)  
VALUES(2,'Marina Oliveira','98765432100');  
INSERT INTO PESSOAS_CONTATO(CODIGO_PESSOA_CONTATO,NOME_PESSOA_CONTATO ,CPF_PESSOA_CONTATO)  
VALUES(3,'Carlos Silva','11223344556');  
INSERT INTO PESSOAS_CONTATO(CODIGO_PESSOA_CONTATO,NOME_PESSOA_CONTATO ,CPF_PESSOA_CONTATO)  
VALUES(4,'Ana Beatriz','66778899000');  
INSERT INTO PESSOAS_CONTATO(CODIGO_PESSOA_CONTATO,NOME_PESSOA_CONTATO ,CPF_PESSOA_CONTATO)  
VALUES(5,'Pedro Henrique','99887766554');  

UPDATE PESSOAS_CONTATO  
SET CPF_PESSOA_CONTATO='12345678901'   
WHERE CODIGO_PESSOA_CONTATO=1;  
UPDATE PESSOAS_CONTATO  
SET NOME_PESSOA_CONTATO='Ana Beatriz Santos'
WHERE CODIGO_PESSOA_CONTATO=4;  

DELETE FROM PESSOAS_CONTATO  
WHERE CODIGO_PESSOA_CONTATO = 5;
INSERT INTO PESSOAS_CONTATO(CODIGO_PESSOA_CONTATO,NOME_PESSOA_CONTATO ,CPF_PESSOA_CONTATO)  
VALUES(5,'Pedro Henrique','99887766554');

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA CARGOS]
#####################################################

INSERT INTO CARGOS (CODIGO_CARGO, NOME_CARGO, DESCRICOES_FUNCOES_CARGO)
VALUES (1, 'Arquiteto de Sistemas', 'Responsável por projetar a arquitetura de sistemas complexos.');
INSERT INTO CARGOS (CODIGO_CARGO, NOME_CARGO, DESCRICOES_FUNCOES_CARGO)
VALUES (2, 'Engenheiro de Dados', 'Responsável pela construção e manutenção de pipelines de dados.');
INSERT INTO CARGOS (CODIGO_CARGO, NOME_CARGO, DESCRICOES_FUNCOES_CARGO)
VALUES (3, 'Cientista de Dados', 'Responsável por análises avançadas e modelagem preditiva.');
INSERT INTO CARGOS (CODIGO_CARGO, NOME_CARGO, DESCRICOES_FUNCOES_CARGO)
VALUES (4, 'Analista de Segurança', 'Responsável por garantir a segurança da informação.');
INSERT INTO CARGOS (CODIGO_CARGO, NOME_CARGO, DESCRICOES_FUNCOES_CARGO)
VALUES (5, 'Gerente de Projetos', 'Responsável pela gestão de projetos e equipes.');

UPDATE CARGOS 
SET NOME_CARGO = 'Arquiteto de Software' 
WHERE CODIGO_CARGO = 1;
UPDATE CARGOS 
SET DESCRICOES_FUNCOES_CARGO = 'Responsável por proteger redes e sistemas.' 
WHERE CODIGO_CARGO = 4;

DELETE FROM CARGOS 
WHERE CODIGO_CARGO = 5;
INSERT INTO CARGOS (CODIGO_CARGO, NOME_CARGO, DESCRICOES_FUNCOES_CARGO)
VALUES (5, 'Gerente de Projetos', 'Responsável pela gestão de projetos e equipes.');

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA PRODUTOS]
#####################################################

INSERT INTO PRODUTOS (CODIGO_PRODUTO, NOME_PRODUTO, COR_PRODUTO, DIMENSOES_PRODUTO, PESO_PRODUTO, PRECO_PRODUTO, TEMPO_FABRICACAO_PRODUTO, DESENHO_PRODUTO, HORAS_MAO_DE_OBRA_PRODUTO)
VALUES (1, 'Produto X', 'Azul', '30x30x30', 2.5, 150.00, '7 dias', 'DesenhoX.png', '15 horas');
INSERT INTO PRODUTOS (CODIGO_PRODUTO, NOME_PRODUTO, COR_PRODUTO, DIMENSOES_PRODUTO, PESO_PRODUTO, PRECO_PRODUTO, TEMPO_FABRICACAO_PRODUTO, DESENHO_PRODUTO, HORAS_MAO_DE_OBRA_PRODUTO)
VALUES (2, 'Produto Y', 'Vermelho', '40x40x40', 3.0, 200.00, '10 dias', 'DesenhoY.png', '20 horas');
INSERT INTO PRODUTOS (CODIGO_PRODUTO, NOME_PRODUTO, COR_PRODUTO, DIMENSOES_PRODUTO, PESO_PRODUTO, PRECO_PRODUTO, TEMPO_FABRICACAO_PRODUTO, DESENHO_PRODUTO, HORAS_MAO_DE_OBRA_PRODUTO)
VALUES (3, 'Produto Z', 'Verde', '50x50x50', 4.0, 250.00, '15 dias', 'DesenhoZ.png', '25 horas');
INSERT INTO PRODUTOS (CODIGO_PRODUTO, NOME_PRODUTO, COR_PRODUTO, DIMENSOES_PRODUTO, PESO_PRODUTO, PRECO_PRODUTO, TEMPO_FABRICACAO_PRODUTO, DESENHO_PRODUTO, HORAS_MAO_DE_OBRA_PRODUTO)
VALUES (4, 'Produto W', 'Amarelo', '60x60x60', 5.0, 300.00, '20 dias', 'DesenhoW.png', '30 horas');
INSERT INTO PRODUTOS (CODIGO_PRODUTO, NOME_PRODUTO, COR_PRODUTO, DIMENSOES_PRODUTO, PESO_PRODUTO, PRECO_PRODUTO, TEMPO_FABRICACAO_PRODUTO ,DESENHO_PRODUTO ,HORAS_MAO_DE_OBRA_PRODUTO)
VALUES (5,'Produto Q','Preto','70x70x70' ,6.0 ,350.00 ,'25 dias' ,'DesenhoQ.png','35 horas');

UPDATE PRODUTOS 
SET PRECO_PRODUTO = 180.00 
WHERE CODIGO_PRODUTO = 1;
UPDATE PRODUTOS 
SET COR_PRODUTO = 'Cinza'
WHERE CODIGO_PRODUTO = 5;

DELETE FROM PRODUTOS 
WHERE CODIGO_PRODUTO = 5;
INSERT INTO PRODUTOS (CODIGO_PRODUTO, NOME_PRODUTO, COR_PRODUTO, DIMENSOES_PRODUTO, PESO_PRODUTO, PRECO_PRODUTO, TEMPO_FABRICACAO_PRODUTO ,DESENHO_PRODUTO ,HORAS_MAO_DE_OBRA_PRODUTO)
VALUES (5,'Produto Q','Preto','70x70x70' ,6.0 ,350.00 ,'25 dias' ,'DesenhoQ.png','35 horas');

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA TIPOS_COMPONENTE]
#####################################################

INSERT INTO TIPOS_COMPONENTE (CODIGO_TIPO_COMPONENTE ,NOME_TIPO_COMPONENTE )  
VALUES(1,'Componente Eletrônico');  
INSERT INTO TIPOS_COMPONENTE(CODIGO_TIPO_COMPONENTE,NOME_TIPO_COMPONENTE)  
VALUES(2,'Componente Mecânico');  
INSERT INTO TIPOS_COMPONENTE(CODIGO_TIPO_COMPONENTE,NOME_TIPO_COMPONENTE)  
VALUES(3,'Componente Óptico');  
INSERT INTO TIPOS_COMPONENTE(CODIGO_TIPO_COMPONENTE,NOME_TIPO_COMPONENTE)  
VALUES(4,'Componente Químico');  
INSERT INTO TIPOS_COMPONENTE(CODIGO_TIPO_COMPONENTE,NOME_TIPO_COMPONENTE)  
VALUES(5,'Componente Biológico');  

UPDATE TIPOS_COMPONENTE  
SET NOME_TIPO_COMPONENTE='Componente Eletrônico Avançado'   
WHERE CODIGO_TIPO_COMPONENTE=1;  
UPDATE TIPOS_COMPONENTE  
SET NOME_TIPO_COMPONENTE='Componente Mecânico Pesado'   
WHERE CODIGO_TIPO_COMPONENTE=2;  

DELETE FROM TIPOS_COMPONENTE  
WHERE CODIGO_TIPO_COMPONENTE=5;  
INSERT INTO TIPOS_COMPONENTE(CODIGO_TIPO_COMPONENTE,NOME_TIPO_COMPONENTE)  
VALUES(5,'Componente Biológico');  

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA MAQUINAS]
#####################################################

INSERT INTO MAQUINAS (CODIGO_MAQUINA, TEMPO_VIDA_MAQUINA, DATA_COMPRA_MAQUINA, DATA_FIM_GARANTIA_MAQUINA)
VALUES (1, '10 anos', '2022-01-15', '2025-01-15');
INSERT INTO MAQUINAS (CODIGO_MAQUINA, TEMPO_VIDA_MAQUINA, DATA_COMPRA_MAQUINA, DATA_FIM_GARANTIA_MAQUINA)
VALUES (2, '8 anos', '2021-03-10', '2024-03-10');
INSERT INTO MAQUINAS (CODIGO_MAQUINA, TEMPO_VIDA_MAQUINA, DATA_COMPRA_MAQUINA, DATA_FIM_GARANTIA_MAQUINA)
VALUES (3, '12 anos', '2020-07-20', '2023-07-20');
INSERT INTO MAQUINAS (CODIGO_MAQUINA, TEMPO_VIDA_MAQUINA, DATA_COMPRA_MAQUINA, DATA_FIM_GARANTIA_MAQUINA)
VALUES (4, '15 anos', '2019-09-05', '2022-09-05');
INSERT INTO MAQUINAS (CODIGO_MAQUINA, TEMPO_VIDA_MAQUINA, DATA_COMPRA_MAQUINA, DATA_FIM_GARANTIA_MAQUINA)
VALUES (5, '5 anos', '2023-02-25', '2026-02-25');

UPDATE MAQUINAS
SET TEMPO_VIDA_MAQUINA = '12 anos' 
WHERE CODIGO_MAQUINA = 1;
UPDATE MAQUINAS
SET DATA_FIM_GARANTIA_MAQUINA = '2026-01-15' 
WHERE CODIGO_MAQUINA = 1;

DELETE FROM MAQUINAS 
WHERE CODIGO_MAQUINA = 5;
INSERT INTO MAQUINAS (CODIGO_MAQUINA, TEMPO_VIDA_MAQUINA, DATA_COMPRA_MAQUINA, DATA_FIM_GARANTIA_MAQUINA)
VALUES (5, '5 anos', '2023-02-25', '2026-02-25');

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA ENDERECOS]
#####################################################

INSERT INTO ENDERECOS (CEP_ENDERECO, RUA_ENDERECO, NUMERO_ENDERECO, COMPLEMENTO_ENDERECO, LOGRADOURO_ENDERECO, BAIRRO_ENDERECO, CIDADE_ENDERECO, ESTADO_ENDERECO, CODIGO_TIPO_ENDERECO)
VALUES ('12345-678', 'Rua das Palmeiras', '100', 'Bloco A', 'Residencial', 'Centro', 'São Paulo', 'SP', 1);
INSERT INTO ENDERECOS (CEP_ENDERECO, RUA_ENDERECO, NUMERO_ENDERECO, COMPLEMENTO_ENDERECO, LOGRADOURO_ENDERECO, BAIRRO_ENDERECO, CIDADE_ENDERECO, ESTADO_ENDERECO, CODIGO_TIPO_ENDERECO)
VALUES ('98765-432', 'Av. dos Jacarandás', '2000', '', 'Comercial', 'Jardins', 'Rio de Janeiro', 'RJ', 2);
INSERT INTO ENDERECOS (CEP_ENDERECO, RUA_ENDERECO, NUMERO_ENDERECO, COMPLEMENTO_ENDERECO, LOGRADOURO_ENDERECO, BAIRRO_ENDERECO, CIDADE_ENDERECO, ESTADO_ENDERECO, CODIGO_TIPO_ENDERECO)
VALUES ('11223-445', 'Rua das Acácias', '500', '', 'Industrial', 'Distrito Industrial', 'Campinas', 'SP', 3);
INSERT INTO ENDERECOS (CEP_ENDERECO, RUA_ENDERECO, NUMERO_ENDERECO, COMPLEMENTO_ENDERECO, LOGRADOURO_ENDERECO, BAIRRO_ENDERECO, CIDADE_ENDERECO, ESTADO_ENDERECO,CODIGO_TIPO_ENDERECO)
VALUES ('22334-556','Estrada Rural','S/N','Fazenda','Rural','Zona Rural','Belo Horizonte','MG' ,4);
INSERT INTO ENDERECOS(CEP_ENDERECO,RUA_ENDERECO ,NUMERO_ENDERECO ,COMPLEMENTO_ENDERECO ,LOGRADOURO_ENDERECO ,BAIRRO_ENDERECO ,CIDADE_ENDERECO ,ESTADO_ENDERECO,CODIGO_TIPO_ENDERECO)  
VALUES('33445-667','Alameda dos Pinheiros','300' ,'Bloco B' ,'Corporativo' ,'Vila Nova' ,'Curitiba' ,'PR' ,5);

UPDATE ENDERECOS 
SET BAIRRO_ENDERECO = 'Vila Nova Conceição'
WHERE CODIGO_TIPO_ENDERECO = 1;
UPDATE ENDERECOS 
SET COMPLEMENTO_ENDERECO = 'Bloco C'
WHERE CODIGO_TIPO_ENDERECO = 5;

DELETE FROM ENDERECOS 
WHERE CODIGO_TIPO_ENDERECO = 5;
INSERT INTO ENDERECOS(CEP_ENDERECO,RUA_ENDERECO ,NUMERO_ENDERECO ,COMPLEMENTO_ENDERECO ,LOGRADOURO_ENDERECO ,BAIRRO_ENDERECO ,CIDADE_ENDERECO ,ESTADO_ENDERECO,CODIGO_TIPO_ENDERECO)  
VALUES('33445-667','Alameda dos Pinheiros','300' ,'Bloco B' ,'Corporativo' ,'Vila Nova' ,'Curitiba' ,'PR' ,5);

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA EMPREGADOS]
#####################################################

INSERT INTO EMPREGADOS (MATRICULA_EMPREGADO, NOME_EMPREGADO, CPF_EMPREGADO, SALARIO_EMPREGADO, DATRA_ADMISSAO_EMPREGADO, CODIGO_CARGO_EMPREGADO)
VALUES (1, 'Alfredo Souza', '12345678900', '5000.00', '2023-01-15', 1);
INSERT INTO EMPREGADOS (MATRICULA_EMPREGADO, NOME_EMPREGADO, CPF_EMPREGADO, SALARIO_EMPREGADO, DATRA_ADMISSAO_EMPREGADO, CODIGO_CARGO_EMPREGADO)
VALUES (2, 'Beatriz Lima', '98765432100', '6000.00', '2023-02-20', 2);
INSERT INTO EMPREGADOS (MATRICULA_EMPREGADO, NOME_EMPREGADO, CPF_EMPREGADO, SALARIO_EMPREGADO, DATRA_ADMISSAO_EMPREGADO, CODIGO_CARGO_EMPREGADO)
VALUES (3, 'Carlos Mendes', '11223344556', '7000.00', '2023-03-05', 3);
INSERT INTO EMPREGADOS (MATRICULA_EMPREGADO, NOME_EMPREGADO, CPF_EMPREGADO, SALARIO_EMPREGADO, DATRA_ADMISSAO_EMPREGADO, CODIGO_CARGO_EMPREGADO)
VALUES (4, 'Daniela Souza', '66778899000', '8000.00', '2023-04-10', 4);
INSERT INTO EMPREGADOS (MATRICULA_EMPREGADO, NOME_EMPREGADO, CPF_EMPREGADO, SALARIO_EMPREGADO, DATRA_ADMISSAO_EMPREGADO, CODIGO_CARGO_EMPREGADO)
VALUES (5, 'Eduardo Pereira', '99887766554', '9000.00', '2023-05-25', 5);

UPDATE EMPREGADOS 
SET SALARIO_EMPREGADO = '5500.00' 
WHERE MATRICULA_EMPREGADO = 1;
UPDATE EMPREGADOS 
SET NOME_EMPREGADO = 'Beatriz Lima da Silva' 
WHERE MATRICULA_EMPREGADO = 2;

DELETE FROM EMPREGADOS 
WHERE MATRICULA_EMPREGADO = 5;
INSERT INTO EMPREGADOS (MATRICULA_EMPREGADO, NOME_EMPREGADO, CPF_EMPREGADO, SALARIO_EMPREGADO, DATRA_ADMISSAO_EMPREGADO, CODIGO_CARGO_EMPREGADO)
VALUES (5, 'Eduardo Pereira', '99887766554', '9000.00', '2023-05-25', 5);

#################################################
# | INSERT | UPDATE | DELETE | [TABELA TELEFONES]
#################################################
INSERT INTO TELEFONES (DDD_TEL ,NUMERO_TEL ,CODIGO_CLIENTE)  
VALUES('11','987654321' ,1);  
INSERT INTO TELEFONES(DDD_TEL ,NUMERO_TEL ,CODIGO_FORNECEDOR)  
VALUES('21','912345678' ,2);  
INSERT INTO TELEFONES(DDD_TEL ,NUMERO_TEL ,CODIGO_EMPREGADO)  
VALUES('31','998877665' ,3);  

INSERT INTO TELEFONES(DDD_TEL ,NUMERO_TEL ,CODIGO_PESSOA_CONTATO)  
VALUES('41','934567890' ,4);  
INSERT INTO TELEFONES(DDD_TEL ,NUMERO_TEL ,CODIGO_CLIENTE)  
VALUES('51','923456789' ,5);

UPDATE TELEFONES 
SET NUMERO_TEL = '987654322'
WHERE DDD_TEL = '11' AND NUMERO_TEL = '987654321';
UPDATE TELEFONES 
SET DDD_TEL = '12'
WHERE DDD_TEL = '11';

DELETE FROM TELEFONES 
WHERE DDD_TEL = '51';
INSERT INTO TELEFONES(DDD_TEL ,NUMERO_TEL ,CODIGO_CLIENTE)  
VALUES('51','923456789' ,5);

##################################################
# | INSERT | UPDATE | DELETE | [TABELA ENCOMENDAS]
##################################################

INSERT INTO ENCOMENDAS (Codigo_Encomenda ,Data_Inclusao_Encomenda ,Valor_Total_Encomenda ,Valor_Desconto_Encomenda,Qtd_Parcelas_Encomenda ,ID_Forma_Pagamento_Encomenda,Codigo_Cliente)  
VALUES(1,'2024-01-15','5000.00','500.00' ,5 ,1 ,1);  
INSERT INTO ENCOMENDAS(Codigo_Encomenda ,Data_Inclusao_Encomenda ,Valor_Total_Encomenda ,Valor_Desconto_Encomenda,Qtd_Parcelas_Encomenda ,ID_Forma_Pagamento_Encomenda,Codigo_Cliente)  
VALUES(2,'2024-02-20','3000.00','300.00' ,3 ,2 ,2);  
INSERT INTO ENCOMENDAS(Codigo_Encomenda ,Data_Inclusao_Encomenda ,Valor_Total_Encomenda ,Valor_Desconto_Encomenda,Qtd_Parcelas_Encomenda ,ID_Forma_Pagamento_Encomenda,Codigo_Cliente)  
VALUES(3,'2024-03-05','7000.00','700.00' ,7 ,3 ,3);  
INSERT INTO ENCOMENDAS(Codigo_Encomenda ,Data_Inclusao_Encomenda ,Valor_Total_Encomenda ,Valor_Desconto_Encomenda,Qtd_Parcelas_Encomenda ,ID_Forma_Pagamento_Encomenda,Codigo_Cliente)  
VALUES(4,'2024-04-10','1500.00','150.00', 2, 4, 4); 
INSERT INTO ENCOMENDAS(Codigo_Encomenda ,Data_Inclusao_Encomenda ,Valor_Total_Encomenda ,Valor_Desconto_Encomenda,Qtd_Parcelas_Encomenda ,ID_Forma_Pagamento_Encomenda,Codigo_Cliente)  
VALUES(5,'2024-05-25','2500.00','250.00', 6,  5,  5);

UPDATE ENCOMENDAS
SET Valor_Total_Encomenda = '6000.00'
WHERE Codigo_Encomenda = 1;

UPDATE ENCOMENDAS
SET Qtd_Parcelas_Encomenda = 10
WHERE Codigo_Encomenda = 5;

DELETE FROM ENCOMENDAS
WHERE Codigo_Encomenda = 5;
INSERT INTO ENCOMENDAS(Codigo_Encomenda ,Data_Inclusao_Encomenda ,Valor_Total_Encomenda ,Valor_Desconto_Encomenda,Qtd_Parcelas_Encomenda ,ID_Forma_Pagamento_Encomenda,Codigo_Cliente)  
VALUES(5,'2024-05-25','2500.00','250.00', 6,  5,  5);

###################################################
# | INSERT | UPDATE | DELETE | [TABELA COMPONENTES]
###################################################

INSERT INTO COMPONENTES (CODIGO_COMPONENTE, Codigo_Tipo_Componente, Nome_Componente, Qtd_Estoque_Componente, Preco_Unitario_Componente, Unidade_Componente)
VALUES (1, 1, 'Resistor 10kΩ', '1000', 0.50, 'unidade');
INSERT INTO COMPONENTES (CODIGO_COMPONENTE, Codigo_Tipo_Componente, Nome_Componente, Qtd_Estoque_Componente, Preco_Unitario_Componente, Unidade_Componente)
VALUES (2, 2, 'Parafuso M6x20mm', '5000', 0.10, 'unidade');
INSERT INTO COMPONENTES (CODIGO_COMPONENTE, Codigo_Tipo_Componente, Nome_Componente, Qtd_Estoque_Componente, Preco_Unitario_Componente ,Unidade_Componente)  
VALUES(3 ,3 ,'Lente Óptica','300','50.00' ,'unidade');  
INSERT INTO COMPONENTES(CODIGO_COMPONENTE ,Codigo_Tipo_Componente ,Nome_Componente ,Qtd_Estoque_Componente ,Preco_Unitario_Componente ,Unidade_Componente)  
VALUES(4 ,4 ,'Reagente Químico A','200','100.00' ,'litro');  
INSERT INTO COMPONENTES(CODIGO_COMPONENTE ,Codigo_Tipo_Componente ,Nome_Componente ,Qtd_Estoque_Componente ,Preco_Unitario_Componente ,Unidade_Componente)  
VALUES(5 ,5 ,'Célula Biológica X','50','500.00' ,'unidade');

UPDATE COMPONENTES 
SET Qtd_Estoque_Componente = '1200'
WHERE CODIGO_COMPONENTE = 1;
UPDATE COMPONENTES 
SET Preco_Unitario_Componente = 55.00
WHERE CODIGO_COMPONENTE = 3;

DELETE FROM COMPONENTES 
WHERE CODIGO_COMPONENTE = 5;
INSERT INTO COMPONENTES(CODIGO_COMPONENTE ,Codigo_Tipo_Componente ,Nome_Componente ,Qtd_Estoque_Componente ,Preco_Unitario_Componente ,Unidade_Componente)  
VALUES(5 ,5 ,'Célula Biológica X','50','500.00' ,'unidade');

############################################################
# | INSERT | UPDATE | DELETE | [TABELA Registros_Manutencao]
############################################################

INSERT INTO Registros_Manutencao (Codigo_RM, Data_RM, Desc_RM, ID_Maquina_RM)
VALUES (1, '2024-01-15', 'Troca de peças internas', 1);
INSERT INTO Registros_Manutencao (Codigo_RM, Data_RM, Desc_RM, ID_Maquina_RM)
VALUES (2, '2024-02-20', 'Lubrificação geral', 2);
INSERT INTO Registros_Manutencao (Codigo_RM, Data_RM, Desc_RM, ID_Maquina_RM)
VALUES (3, '2024-03-05', 'Substituição de motor', 3);
INSERT INTO Registros_Manutencao (Codigo_RM, Data_RM, Desc_RM, ID_Maquina_RM)
VALUES (4, '2024-04-10', 'Ajuste de correias e polias', 4);
INSERT INTO Registros_Manutencao (Codigo_RM, Data_RM, Desc_RM, ID_Maquina_RM)
VALUES (5, '2024-05-25', 'Revisão completa de segurança', 5);

UPDATE Registros_Manutencao 
SET Desc_RM = 'Troca completa de peças internas'
WHERE Codigo_RM = 1;
UPDATE Registros_Manutencao 
SET Data_RM = '2024-06-01'
WHERE Codigo_RM = 5;

DELETE FROM Registros_Manutencao 
WHERE Codigo_RM = 5;
INSERT INTO Registros_Manutencao (Codigo_RM, Data_RM, Desc_RM, ID_Maquina_RM)
VALUES (5, '2024-05-25', 'Revisão completa de segurança', 5);

############################################################
# | INSERT | UPDATE | DELETE | [TABELA RECURSOS_ESPECIFICOS]
############################################################

INSERT INTO RECURSOS_ESPECIFICOS (ID_RE, Qntd_NEC_RE, UNID_RE, TEMP_USO_RE, HoraMaoObra_RE, Maquina_RE, COMP_RE, EMPREG_RE, PROD_RE)
VALUES (1, 10, 'unidades', '5 dias', '20 horas', 1, 1, 1, 1);
INSERT INTO RECURSOS_ESPECIFICOS (ID_RE, Qntd_NEC_RE, UNID_RE, TEMP_USO_RE, HoraMaoObra_RE, Maquina_RE, COMP_RE, EMPREG_RE, PROD_RE)
VALUES (2, 15, 'litros', '3 dias', '15 horas', 2, 2, 2, 2);
INSERT INTO RECURSOS_ESPECIFICOS (ID_RE, Qntd_NEC_RE ,UNID_RE ,TEMP_USO_RE ,HoraMaoObra_RE ,Maquina_RE ,COMP_RE ,EMPREG_RE ,PROD_RE)  
VALUES(3 ,20 ,'metros' ,'7 dias' ,'25 horas' ,3 ,3 ,3 ,3);  
INSERT INTO RECURSOS_ESPECIFICOS(ID_RE ,Qntd_NEC_RE ,UNID_RE ,TEMP_USO_RE ,HoraMaoObra_RE ,Maquina_RE ,COMP_RE ,EMPREG_RE ,PROD_RE)  
VALUES(4 ,30 ,'quilos' ,'10 dias' ,'30 horas' ,4 ,4 ,4 ,4);  
INSERT INTO RECURSOS_ESPECIFICOS(ID_RE ,Qntd_NEC_RE ,UNID_RE ,TEMP_USO_RE ,HoraMaoObra_RE ,Maquina_RE ,COMP_RE ,EMPREG_RE ,PROD_RE)  
VALUES(5,  50,  'unidades'  ,'12 dias'  ,'35 horas', 5, 5, 5, 5);

UPDATE RECURSOS_ESPECIFICOS  
SET Qntd_NEC_RE=25   
WHERE ID_RE=1;  
UPDATE RECURSOS_ESPECIFICOS  
SET TEMP_USO_RE='8 dias'   
WHERE ID_RE=3;  

DELETE FROM RECURSOS_ESPECIFICOS  
WHERE ID_RE=5;  
INSERT INTO RECURSOS_ESPECIFICOS(ID_RE ,Qntd_NEC_RE ,UNID_RE ,TEMP_USO_RE ,HoraMaoObra_RE ,Maquina_RE ,COMP_RE ,EMPREG_RE ,PROD_RE)  
VALUES(5,  50,  'unidades'  ,'12 dias'  ,'35 horas', 5, 5, 5, 5);

############################################################
# | INSERT | UPDATE | DELETE | [TABELA REGISTROS_SUPRIMENTO]
############################################################

INSERT INTO REGISTROS_SUPRIMENTO (RegistSupri_PROD, RegistSupri_COMP, RegistSupri_QTD, RegistSupri_DATA_NEC)
VALUES (1, 1, 1000, '2024-01-15');
INSERT INTO REGISTROS_SUPRIMENTO (RegistSupri_PROD, RegistSupri_COMP, RegistSupri_QTD, RegistSupri_DATA_NEC)
VALUES (2, 2, 5000,'2024-02-20');
INSERT INTO REGISTROS_SUPRIMENTO(RegistSupri_PROD, RegistSupri_COMP, RegistSupri_QTD ,RegistSupri_DATA_NEC)  
VALUES(3, 3, 3000,'2024-03-05');  

INSERT INTO REGISTROS_SUPRIMENTO(RegistSupri_PROD, RegistSupri_COMP, RegistSupri_QTD, RegistSupri_DATA_NEC)  
VALUES(4, 4, 5000, '2024-04-10');
INSERT INTO REGISTROS_SUPRIMENTO(RegistSupri_PROD,  RegistSupri_COMP, RegistSupri_QTD, RegistSupri_DATA_NEC)  
VALUES(5, 5, 7000,'2024-05-25');

UPDATE REGISTROS_SUPRIMENTO  
SET RegistSupri_QTD=1200   
WHERE RegistSupri_PROD=1 AND RegistSupri_COMP= 1;  
UPDATE REGISTROS_SUPRIMENTO  
SET RegistSupri_DATA_NEC='2024-06-01'   
WHERE RegistSupri_PROD=5 AND RegistSupri_COMP= 5;  

DELETE FROM REGISTROS_SUPRIMENTO WHERE RegistSupri_PROD=5 AND RegistSupri_COMP= 5;
INSERT INTO REGISTROS_SUPRIMENTO(RegistSupri_PROD,  RegistSupri_COMP, RegistSupri_QTD, RegistSupri_DATA_NEC) VALUES(5, 5, 7000,'2024-05-25');

###########################################################
# | INSERT | UPDATE | DELETE | [TABELA PRODUTOS_ENCOMENDAS]
###########################################################

INSERT INTO PRODUTOS_ENCOMENDAS (ProdEncomend_PROD ,ProdEncomend_ENCOM)  
VALUES(1, 1);  
INSERT INTO PRODUTOS_ENCOMENDAS(ProdEncomend_PROD ,ProdEncomend_ENCOM)  
VALUES(2, 2);
INSERT INTO PRODUTOS_ENCOMENDAS(ProdEncomend_PROD ,ProdEncomend_ENCOM)  
VALUES(3, 3);  
INSERT INTO PRODUTOS_ENCOMENDAS(ProdEncomend_PROD ,ProdEncomend_ENCOM)  
VALUES(4, 4);
INSERT INTO PRODUTOS_ENCOMENDAS(ProdEncomend_PROD ,ProdEncomend_ENCOM)  
VALUES(5, 5); 		

UPDATE PRODUTOS_ENCOMENDAS  
SET ProdEncomend_PROD= 2
WHERE ProdEncomend_ENCOM= 1;  
UPDATE PRODUTOS_ENCOMENDAS  
SET ProdEncomend_ENCOM= 4
WHERE ProdEncomend_PROD= 3;  

DELETE FROM PRODUTOS_ENCOMENDAS  
WHERE ProdEncomend_PROD= 5;
INSERT INTO PRODUTOS_ENCOMENDAS(ProdEncomend_PROD ,ProdEncomend_ENCOM)  
VALUES(5 , 5);

################################################################
# | INSERT | UPDATE | DELETE | [TABELA COMPONENTES_FORNECEDORES]
################################################################

INSERT INTO COMPONENTES_FORNECEDORES (CompForn_COMP, CompForn_FORN)
VALUES (1, 1);
INSERT INTO COMPONENTES_FORNECEDORES (CompForn_COMP, CompForn_FORN)
VALUES (2, 2); 
INSERT INTO COMPONENTES_FORNECEDORES (CompForn_COMP, CompForn_FORN)
VALUES (3, 3);
INSERT INTO COMPONENTES_FORNECEDORES (CompForn_COMP, CompForn_FORN)
VALUES (4, 4);
INSERT INTO COMPONENTES_FORNECEDORES (CompForn_COMP, CompForn_FORN)
VALUES (5, 5);

UPDATE COMPONENTES_FORNECEDORES SET CompForn_FORN = 1 WHERE CompForn_COMP = 2; 
UPDATE COMPONENTES_FORNECEDORES  SET CompForn_COMP = 4 WHERE CompForn_FORN = 3;

DELETE FROM COMPONENTES_FORNECEDORES WHERE CompForn_COMP = 5 AND CompForn_FORN = 5;
INSERT INTO COMPONENTES_FORNECEDORES (CompForn_COMP, CompForn_FORN) VALUES (5, 5);
