# ##################################################################################################### #
#                                                                                                       #
#                                                  DML                                                  #
#                                                                                                       #
# ##################################################################################################### #
USE EST_CASO_IV;
#####################################################
# | INSERT | UPDATE | DELETE | [TABELA INSTRUTORES]
#####################################################

INSERT INTO INSTRUTORES (ID_INSTRUTOR, NOME_INSTRUTOR, CPF_INSTRUTOR, EMAIL_INSTRUTOR) 
VALUES (1, 'Aurelio Dicionério Translator de Guugol', '123.456.789-00', 'aurelio.translator@email.com');
INSERT INTO INSTRUTORES (ID_INSTRUTOR, NOME_INSTRUTOR, CPF_INSTRUTOR, EMAIL_INSTRUTOR) 
VALUES (2, 'Berenilde Oleosa', '987.654.321-11', 'X1Noob_caminhao.oliveira@email.com');
INSERT INTO INSTRUTORES (ID_INSTRUTOR, NOME_INSTRUTOR, CPF_INSTRUTOR, EMAIL_INSTRUTOR) 
VALUES (3, 'Gustavo Cecilio', '111.222.333-44', 'Gusce.andrade@email.com');
INSERT INTO INSTRUTORES (ID_INSTRUTOR, NOME_INSTRUTOR, CPF_INSTRUTOR, EMAIL_INSTRUTOR) 
VALUES (4, 'Dora a Perneta', '555.666.777-88', 'dorinha69.pereira@email.com');
INSERT INTO INSTRUTORES (ID_INSTRUTOR, NOME_INSTRUTOR, CPF_INSTRUTOR, EMAIL_INSTRUTOR) 
VALUES (5, 'Furico Da Silva', '999.888.777-66', 'furico.silva@email.com');

UPDATE INSTRUTORES 
SET EMAIL_INSTRUTOR = 'ar.translator@email.com' 
WHERE ID_INSTRUTOR = 1;
UPDATE INSTRUTORES 
SET NOME_INSTRUTOR = 'Oliveira Zé Ruela me Paga oq Deve' 
WHERE ID_INSTRUTOR = 2;

DELETE FROM INSTRUTORES 
WHERE ID_INSTRUTOR = 5;
INSERT INTO INSTRUTORES (ID_INSTRUTOR, NOME_INSTRUTOR, CPF_INSTRUTOR, EMAIL_INSTRUTOR) 
VALUES (5, 'Furico Da Silva', '999.888.777-66', 'furico.silva@email.com');

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA MODALIDADES]
#####################################################

INSERT INTO MODALIDADES (ID_MODALIDADE, NOME_MODALIDADE) 
VALUES (1, 'Musculação');
INSERT INTO MODALIDADES (ID_MODALIDADE, NOME_MODALIDADE) 
VALUES (2, 'Crossfit');
INSERT INTO MODALIDADES (ID_MODALIDADE, NOME_MODALIDADE) 
VALUES (3, 'Pilates');
INSERT INTO MODALIDADES (ID_MODALIDADE, NOME_MODALIDADE) 
VALUES (4, 'Yoga');
INSERT INTO MODALIDADES (ID_MODALIDADE, NOME_MODALIDADE) 
VALUES (5, 'Boxe');

UPDATE MODALIDADES 
SET NOME_MODALIDADE = 'Fuga da Policia Simulada' 
WHERE ID_MODALIDADE = 2;
UPDATE MODALIDADES 
SET NOME_MODALIDADE = 'Briga de Rua' 
WHERE ID_MODALIDADE = 5;

DELETE FROM MODALIDADES 
WHERE ID_MODALIDADE = 5;
INSERT INTO MODALIDADES (ID_MODALIDADE, NOME_MODALIDADE) 
VALUES (5, 'Briga de Rua');

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA ALUNOS]
#####################################################

INSERT INTO ALUNOS (ID_ALUNO, NOME_ALUNO, CPF_ALUNO, DATA_NASC_ALUNO, CEP_ALUNO, RUA_ALUNO, NUM_RES_ALUNO, BAIRRO_ALUNO, CIDADE_ALUNO, UF_ALUNO)
VALUES (1, 'Fernanda Costela de Adão', '123.456.789-00', '1990-05-15', '12345-678', 'Rua das Flores', 1010, 'Centro', 'São Paulo', 'SP');
INSERT INTO ALUNOS (ID_ALUNO, NOME_ALUNO, CPF_ALUNO, DATA_NASC_ALUNO, CEP_ALUNO, RUA_ALUNO, NUM_RES_ALUNO, BAIRRO_ALUNO, CIDADE_ALUNO, UF_ALUNO)
VALUES (2, 'Gustavo Almeidão do Povo', '987.654.321-11', '1985-08-20', '87654-321', 'Avenida Paulista', 2020, 'Bela Vista', 'São Paulo', 'SP');
INSERT INTO ALUNOS (ID_ALUNO, NOME_ALUNO, CPF_ALUNO, DATA_NASC_ALUNO, CEP_ALUNO, RUA_ALUNO, NUM_RES_ALUNO, BAIRRO_ALUNO, CIDADE_ALUNO, UF_ALUNO)
VALUES (3, 'Helena Solta das Quantas', '111.222.333-44', '1992-12-10', '54321-987', 'Rua das Palmeiras', 3030, 'Jardins', 'São Paulo', 'SP');
INSERT INTO ALUNOS (ID_ALUNO, NOME_ALUNO, CPF_ALUNO, DATA_NASC_ALUNO, CEP_ALUNO, RUA_ALUNO, NUM_RES_ALUNO, BAIRRO_ALUNO, CIDADE_ALUNO, UF_ALUNO)
VALUES (4, 'Igor Fernandinho Pé de Vento', '555.666.777-88', '1980-03-05', '65432-123', 'Rua do Sol', 4040, 'Moema', 'São Paulo', 'SP');
INSERT INTO ALUNOS (ID_ALUNO, NOME_ALUNO, CPF_ALUNO, DATA_NASC_ALUNO, CEP_ALUNO, RUA_ALUNO , NUM_RES_ALUNO , BAIRRO_ALUNO , CIDADE_ALUNO , UF_ALUNO)
VALUES (5,'Juliana Queima-Anel de Sauron da Silva','999.888.777-66','1995-07-25','76543-210','Avenida Brasilia ',5050,'Vila Mariana','São Paulo','SP');

UPDATE ALUNOS 
SET CEP_ALUNO = '11111-222' 
WHERE ID_ALUNO = 1;
UPDATE ALUNOS 
SET CIDADE_ALUNO = "Rio de Janeiro" 
WHERE ID_ALUNO = 4;

DELETE FROM ALUNOS 
WHERE ID_ALUNO = 5;
INSERT INTO ALUNOS (ID_ALUNO, NOME_ALUNO, CPF_ALUNO, DATA_NASC_ALUNO, CEP_ALUNO, RUA_ALUNO , NUM_RES_ALUNO , BAIRRO_ALUNO , CIDADE_ALUNO , UF_ALUNO)
VALUES (5,'Juliana Queima-Anel de Sauron da Silva','999.888.777-66','1995-07-25','76543-210','Avenida Brasilia ',5050,'Vila Mariana','São Paulo','SP');

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA AULAS]
#####################################################

INSERT INTO AULAS (ID_AULA, HORA_AULA, DIA_AULA, CAPAC_AULA, INSTRUTOR_AULA, MODALIDADE_AULA)
VALUES (1, '08:00:00', 'SEGUNDA', 20, 1, 1);
INSERT INTO AULAS (ID_AULA, HORA_AULA, DIA_AULA, CAPAC_AULA, INSTRUTOR_AULA, MODALIDADE_AULA)
VALUES (2, '09:00:00', 'TERCA', 15, 2, 2);
INSERT INTO AULAS (ID_AULA, HORA_AULA, DIA_AULA, CAPAC_AULA, INSTRUTOR_AULA, MODALIDADE_AULA)
VALUES (3, '10:00:00', 'QUARTA', 25, 3, 3);
INSERT INTO AULAS (ID_AULA, HORA_AULA, DIA_AULA, CAPAC_AULA, INSTRUTOR_AULA, MODALIDADE_AULA)
VALUES (4, '11:00:00', 'QUINTA', 30, 4, 4);
INSERT INTO AULAS (ID_AULA, HORA_AULA, DIA_AULA, CAPAC_AULA, INSTRUTOR_AULA, MODALIDADE_AULA)
VALUES (5, '12:00:00', 'SEXTA', 20, 5, 5);

UPDATE AULAS 
SET CAPAC_AULA = 35 
WHERE ID_AULA = 1;
UPDATE AULAS 
SET DIA_AULA = 'SABADO' 
WHERE ID_AULA = 2;

DELETE FROM AULAS 
WHERE ID_AULA = 5;
INSERT INTO AULAS (ID_AULA, HORA_AULA, DIA_AULA, CAPAC_AULA, INSTRUTOR_AULA, MODALIDADE_AULA)
VALUES (5, '12:00:00', 'SEXTA', 20, 5, 5);

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA PLANOS_TREINAMENTO]
#####################################################

INSERT INTO PLANOS_TREINAMENTO (ID_PLAN, STATUS_PLAN, INSTRUTOR_PLAN, ALUNO_PLAN)
VALUES (1, 'ATIVO', 1, 1);
INSERT INTO PLANOS_TREINAMENTO (ID_PLAN, STATUS_PLAN, INSTRUTOR_PLAN, ALUNO_PLAN)
VALUES (2, 'INATIVO', 2, 2);
INSERT INTO PLANOS_TREINAMENTO (ID_PLAN, STATUS_PLAN, INSTRUTOR_PLAN, ALUNO_PLAN)
VALUES (3, 'ATIVO', 3, 3);
INSERT INTO PLANOS_TREINAMENTO (ID_PLAN, STATUS_PLAN, INSTRUTOR_PLAN, ALUNO_PLAN)
VALUES (4, 'ATIVO', 4, 4);
INSERT INTO PLANOS_TREINAMENTO (ID_PLAN, STATUS_PLAN, INSTRUTOR_PLAN , ALUNO_PLAN )
VALUES (5,'INATIVO',5 ,5);

UPDATE PLANOS_TREINAMENTO 
SET STATUS_PLAN = 'ATIVO' 
WHERE ID_PLAN = 2;
UPDATE PLANOS_TREINAMENTO 
SET INSTRUTOR_PLAN = 3 
WHERE ID_PLAN = 4;

DELETE FROM PLANOS_TREINAMENTO 
WHERE ID_PLAN = 5;
INSERT INTO PLANOS_TREINAMENTO (ID_PLAN, STATUS_PLAN, INSTRUTOR_PLAN , ALUNO_PLAN )
VALUES (5,'INATIVO',5 ,5);

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA PAGAMENTOS]
#####################################################

INSERT INTO PAGAMENTOS (ID_PAG , DATA_PAG , STATUS_PAG , VALOR_PAG , ALUNO_PAG )
VALUES (1,'2024-01-10','PAGO',30.50 ,1);
INSERT INTO PAGAMENTOS (ID_PAG , DATA_PAG , STATUS_PAG , VALOR_PAG , ALUNO_PAG )
VALUES (2,'2024-02-15','PENDENTE',20.00 ,2);
INSERT INTO PAGAMENTOS (ID_PAG , DATA_PAG , STATUS_PAG , VALOR_PAG , ALUNO_PAG )
VALUES (3,'2024-03-20','PAGO',25.75 ,3);
INSERT INTO PAGAMENTOS (ID_PAG , DATA_PAG , STATUS_PAG , VALOR_PAG , ALUNO_PAG )
VALUES (4,'2024-04-25','PAGO',28.60 ,4);
INSERT INTO PAGAMENTOS (ID_PAG , DATA_PAG , STATUS_PAG , VALOR_PAG , ALUNO_PAG )
VALUES(5,'2024-05-30','PENDENTE',30.90 ,5);

UPDATE PAGAMENTOS 
SET STATUS_PAG = 'PAGO' 
WHERE ID_PAG = 2;
UPDATE PAGAMENTOS 
SET VALOR_PAG = 32.90 
WHERE ID_PAG = 5;

DELETE FROM PAGAMENTOS 
WHERE ID_PAG = 5;
INSERT INTO PAGAMENTOS (ID_PAG , DATA_PAG , STATUS_PAG , VALOR_PAG , ALUNO_PAG )
VALUES(5,'2024-05-30','PENDENTE',30.90 ,5);

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA ALUNOS_AULAS]
#####################################################

INSERT INTO ALUNOS_AULAS (AU_AL_AULA, AU_AL_ALUNO)
VALUES (1, 1);
INSERT INTO ALUNOS_AULAS (AU_AL_AULA, AU_AL_ALUNO)
VALUES (2, 2);
INSERT INTO ALUNOS_AULAS (AU_AL_AULA, AU_AL_ALUNO)
VALUES (3, 3);
INSERT INTO ALUNOS_AULAS (AU_AL_AULA, AU_AL_ALUNO)
VALUES (4, 4);
INSERT INTO ALUNOS_AULAS (AU_AL_AULA, AU_AL_ALUNO)
VALUES (5, 5);

UPDATE ALUNOS_AULAS 
SET AU_AL_AULA = 2 
WHERE AU_AL_ALUNO = 1;
UPDATE ALUNOS_AULAS 
SET AU_AL_ALUNO = 3 
WHERE AU_AL_AULA = 4;

DELETE FROM ALUNOS_AULAS 
WHERE AU_AL_AULA = 5 AND AU_AL_ALUNO = 5;
INSERT INTO ALUNOS_AULAS (AU_AL_AULA, AU_AL_ALUNO)
VALUES (5, 5);
