#drop schema ec2_cc1m;
CREATE SCHEMA EC2_CC1M;

USE EC2_CC1M;



# ################################################################################# #
# 																					#
# 										DDL											#
# 																					#
# ################################################################################# #
# CRIANDO AS TABELAS SEM CHAVES ESTRANGEIRAS
# #######################################################################################
# ##############################| CRIANDO A TABELA PASSAGEIROS |#########################
# #######################################################################################
CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF VARCHAR(14) PRIMARY KEY,
PASS_NOME VARCHAR(50) NOT NULL,
PASS_TEL VARCHAR(15) NOT NULL,
PASS_ENDRC TEXT NOT NULL,
PASS_EMAIL VARCHAR(30) NOT NULL
);
#DAR COMANDOS DE ALTER NA TABELA PASSAGEIROS
ALTER TABLE PASSAGEIROS ADD column DESCRICAO_PASSAGEIROS TEXT NOT NULL;
ALTER TABLE PASSAGEIROS MODIFY COLUMN DESCRICAO_PASSAGEIROS VARCHAR(100);
ALTER TABLE PASSAGEIROS CHANGE COLUMN DESCRICAO_PASSAGEIROS DESCRICAO_PASSAGEIROS1 VARCHAR(100);
ALTER TABLE PASSAGEIROS DROP COLUMN DESCRICAO_PASSAGEIROS1;
# ######################################################################################
# ##############################| CRIANDO A TABELA AEROPORTOS |#########################
# ######################################################################################
CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_COD INT PRIMARY KEY,
AEROP_NOME VARCHAR(20) NOT NULL,
AEROP_CIDADE VARCHAR(20) NOT NULL,
AEROP_PAIS VARCHAR(20) NOT NULL,
AEROP_LAT DECIMAL(2,2) NOT NULL,
AEROP_LONG DECIMAL(3,2) NOT NULL 
);
#DAR COMANDOS DE ALTER NA TABELA AEROPORTOS
ALTER TABLE AEROPORTOS ADD column DESCRICAO_AEROPORTOS TEXT NOT NULL;
ALTER TABLE AEROPORTOS MODIFY COLUMN DESCRICAO_AEROPORTOS VARCHAR(100);
ALTER TABLE AEROPORTOS CHANGE COLUMN DESCRICAO_AEROPORTOS DESCRICAO_AEROPORTOS1 VARCHAR(100);
ALTER TABLE AEROPORTOS DROP COLUMN DESCRICAO_AEROPORTOS1;

ALTER TABLE AEROPORTOS MODIFY COLUMN AEROP_LAT DECIMAL(9,6);
ALTER TABLE AEROPORTOS MODIFY COLUMN AEROP_LONG DECIMAL(9,6);

# #####################################################################################
# ##############################| CRIANDO A TABELA AERONAVES |#########################
# #####################################################################################
CREATE TABLE IF NOT EXISTS AERONAVES(
AERON_PREFX VARCHAR(10) PRIMARY KEY,
AERON_MODELO VARCHAR(20) NOT NULL,
AERON_ANOFABR INT NOT NULL,
AERON_AUTON DECIMAL(3,2) NOT NULL,
AERON_CAPAC INT NOT NULL,
AERON_FABRNT VARCHAR(20) NOT NULL
);
#DAR COMANDOS DE ALTER NA TABELA AERONAVES
ALTER TABLE AERONAVES ADD column DESCRICAO_AERONAVES TEXT NOT NULL;
ALTER TABLE AERONAVES MODIFY COLUMN DESCRICAO_AERONAVES VARCHAR(100);
ALTER TABLE AERONAVES CHANGE COLUMN DESCRICAO_AERONAVES DESCRICAO_AERONAVES1 VARCHAR(100);
ALTER TABLE AERONAVES DROP COLUMN DESCRICAO_AERONAVES1;
# #####################################################################################
# ##############################| CRIANDO A TABELA FUNCIONARIOS |######################
# #####################################################################################
CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_NOME VARCHAR(40) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_ENDRC TEXT NOT NULL,
FUNC_CPF VARCHAR(14) NOT NULL,
FUNC_FUNCAO TEXT NOT NULL
);
#DAR COMANDOS DE ALTER NA TABELA FUNCIONARIOS
ALTER TABLE FUNCIONARIOS ADD column DESCRI_FUNCIONARIOS TEXT NOT NULL;
ALTER TABLE FUNCIONARIOS MODIFY COLUMN DESCRI_FUNCIONARIOS VARCHAR(100);
ALTER TABLE FUNCIONARIOS CHANGE COLUMN DESCRI_FUNCIONARIOS DESCRI_FUNCIONARIOS1 VARCHAR(100);
ALTER TABLE FUNCIONARIOS DROP COLUMN DESCRI_FUNCIONARIOS1;
# #############################################################################
# ##############################| CRIANDO A TABELA VOOS |######################
# #############################################################################
CREATE TABLE IF NOT EXISTS VOOS(
VOO_ID INT PRIMARY KEY,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AERON VARCHAR(10) NOT NULL,
VOO_AEROP INT NOT NULL,
CONSTRAINT FK_AERONAVES FOREIGN KEY (VOO_AERON) REFERENCES AERONAVES(AERON_PREFX),
CONSTRAINT FK_AEROPORTOS FOREIGN KEY (VOO_AEROP) REFERENCES AEROPORTOS(AEROP_COD)
);
#DAR COMANDOS DE ALTER NA TABELA VOOS
ALTER TABLE VOOS ADD column DESCRICAO_VOOS TEXT NOT NULL;
ALTER TABLE VOOS MODIFY COLUMN DESCRICAO_VOOS VARCHAR(100);
ALTER TABLE VOOS CHANGE COLUMN DESCRICAO_VOOS DESCRICAO_VOOS1 VARCHAR(100);
ALTER TABLE VOOS DROP COLUMN DESCRICAO_VOOS1;
# #################################################################################
# ##############################| CRIANDO A TABELA RESERVAS |######################
# #################################################################################
CREATE TABLE IF NOT EXISTS RESERVAS(
RESERV_COD INT PRIMARY KEY,
RESERV_VOO INT NOT NULL,
RESERV_PASS VARCHAR(14) NOT NULL,
CONSTRAINT FK_VOOS FOREIGN KEY (RESERV_VOO) REFERENCES VOOS(VOO_ID),
CONSTRAINT FK_PASSAGEIROS FOREIGN KEY (RESERV_PASS) REFERENCES PASSAGEIROS(PASS_CPF)
);
#DAR COMANDOS DE ALTER NA TABELA RESERVAS
ALTER TABLE RESERVAS ADD column DESCRI_RESERVAS TEXT NOT NULL;
ALTER TABLE RESERVAS MODIFY COLUMN DESCRI_RESERVAS VARCHAR(100);
ALTER TABLE RESERVAS CHANGE COLUMN DESCRI_RESERVAS DESCRI_RESERVAS1 VARCHAR(100);
ALTER TABLE RESERVAS DROP COLUMN DESCRI_RESERVAS1;
# #################################################################################
# ##############################| CRIANDO A TABELA VOOS_FUNCIONARIOS |#############
# #################################################################################
CREATE TABLE IF NOT EXISTS VOOS_FUNCIONARIOS(
VSFN_VOOS INT,
VSFN_FUNCIONARIOS INT,
PRIMARY KEY(VSFN_VOOS,VSFN_FUNCIONARIOS),
CONSTRAINT VSFN_FK_VOOS FOREIGN KEY (VSFN_VOOS) REFERENCES VOOS(VOO_ID),
CONSTRAINT VSFN_FK_FUNCIONARIOS FOREIGN KEY (VSFN_FUNCIONARIOS) REFERENCES FUNCIONARIOS(FUNC_ID)
);
#DAR COMANDOS DE ALTER NA TABELA VOOS_FUNCIONARIOS
ALTER TABLE VOOS_FUNCIONARIOS ADD column DESCR_VOOS_FUNCIONARIOS TEXT NOT NULL;
ALTER TABLE VOOS_FUNCIONARIOS MODIFY COLUMN DESCR_VOOS_FUNCIONARIOS VARCHAR(100);
ALTER TABLE VOOS_FUNCIONARIOS CHANGE COLUMN DESCR_VOOS_FUNCIONARIOS DESCR_VOOS_FUNCIONARIOS VARCHAR(100);
ALTER TABLE VOOS_FUNCIONARIOS DROP COLUMN DESCR_VOOS_FUNCIONARIOS;

# ################################################################################# #
# 																					#
# 										DML											#
# 																					#
# ################################################################################# #

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA PASSAGEIROS]
#####################################################
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TEL, PASS_ENDRC, PASS_EMAIL) 
VALUES ('123.456.789-00', 'João Silva', '(11) 98765-4321', 'Rua A, 123', 'joao.silva@email.com');
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TEL, PASS_ENDRC, PASS_EMAIL) 
VALUES ('987.654.321-00', 'Maria Oliveira', '(21) 91234-5678', 'Rua B, 456', 'maria.oliveira@email.com');
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TEL, PASS_ENDRC, PASS_EMAIL) 
VALUES ('111.222.333-44', 'Carlos Souza', '(31) 99876-5432', 'Rua C, 789', 'carlos.souza@email.com');
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TEL, PASS_ENDRC, PASS_EMAIL) 
VALUES ('555.666.777-88', 'Ana Costa', '(41) 92345-6789', 'Rua D, 321', 'ana.costa@email.com');
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TEL, PASS_ENDRC, PASS_EMAIL) 
VALUES ('999.888.777-66', 'Pedro Lima', '(51) 93456-7890', 'Rua E, 654', 'pedro.lima@email.com');

UPDATE PASSAGEIROS
SET PASS_TEL = '(11) 91234-5678'
WHERE PASS_CPF = '123.456.789-00';

UPDATE PASSAGEIROS
SET PASS_EMAIL = 'joao.novo@email.com'
WHERE PASS_CPF = '123.456.789-00';

DELETE FROM PASSAGEIROS 
WHERE PASS_CPF = '999.888.777-66'; # CPF Cancelado
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TEL, PASS_ENDRC, PASS_EMAIL) 
VALUES ('999.888.777-66', 'Pedro Lima', '(51) 93456-7890', 'Rua E, 654', 'pedro.lima@email.com'); # CPF descancelado pelo milagre de SQL!

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA AEROPORTOS]
#####################################################

ALTER TABLE AEROPORTOS 
MODIFY COLUMN AEROP_LAT DECIMAL(9,6),
MODIFY COLUMN AEROP_LONG DECIMAL(9,6);
INSERT INTO AEROPORTOS (AEROP_COD, AEROP_NOME, AEROP_CIDADE, AEROP_PAIS, AEROP_LAT, AEROP_LONG)
VALUES (1, 'Aeroporto SP', 'São Paulo', 'Brasil', -23.63, -46.65);
INSERT INTO AEROPORTOS (AEROP_COD, AEROP_NOME, AEROP_CIDADE, AEROP_PAIS, AEROP_LAT, AEROP_LONG)
VALUES (2, 'Aeroporto RJ', 'Rio de Janeiro', 'Brasil', -22.81, -43.25);
INSERT INTO AEROPORTOS (AEROP_COD, AEROP_NOME, AEROP_CIDADE, AEROP_PAIS, AEROP_LAT, AEROP_LONG)
VALUES (3, 'Aeroporto BH', 'Belo Horizonte', 'Brasil', -19.85, -43.95);
INSERT INTO AEROPORTOS (AEROP_COD, AEROP_NOME, AEROP_CIDADE, AEROP_PAIS, AEROP_LAT, AEROP_LONG)
VALUES (4, 'Aeroporto POA', 'Porto Alegre', 'Brasil', -29.99, -51.17);
INSERT INTO AEROPORTOS (AEROP_COD, AEROP_NOME, AEROP_CIDADE, AEROP_PAIS, AEROP_LAT, AEROP_LONG)
VALUES (5, 'Aeroporto SSA', 'Salvador', 'Brasil', -12.91, -38.33);

#select * from aeroportos;
UPDATE AEROPORTOS 
SET AEROP_NOME = 'Aeroporto Avião-Bala' 
WHERE AEROP_COD = 2;

UPDATE AEROPORTOS
SET AEROP_LAT = -23.55, AEROP_LONG = -46.63
WHERE AEROP_COD = 1;

DELETE FROM AEROPORTOS 
WHERE AEROP_COD = 5;
INSERT INTO AEROPORTOS (AEROP_COD, AEROP_NOME, AEROP_CIDADE, AEROP_PAIS, AEROP_LAT, AEROP_LONG)
VALUES (5, 'Aeroporto SSA', 'Salvador', 'Brasil', -12.91, -38.33);
#####################################################
# | INSERT | UPDATE | DELETE | [TABELA AERONAVES]
#####################################################
INSERT INTO AERONAVES (AERON_PREFX, AERON_MODELO, AERON_ANOFABR, AERON_AUTON, AERON_CAPAC, AERON_FABRNT)
VALUES ('PR-ABC', 'Boeing 737', 2015, 6.5 , 180 , 'Boeing');
INSERT INTO AERONAVES (AERON_PREFX ,AERON_MODELO ,AERON_ANOFABR ,AERON_AUTON ,AERON_CAPAC ,AERON_FABRNT)
VALUES ('PR-DEF' ,'Airbus A320' ,2018 ,5.0 ,160 ,'Airbus');
INSERT INTO AERONAVES (AERON_PREFX ,AERON_MODELO ,AERON_ANOFABR ,AERON_AUTON ,AERON_CAPAC ,AERON_FABRNT)
VALUES ('PR-GHI' ,'Embraer E195' ,2020 ,4.5 ,132 ,'Embraer');
INSERT INTO AERONAVES (AERON_PREFX ,AERON_MODELO ,AERON_ANOFABR ,AERON_AUTON ,AERON_CAPAC ,AERON_FABRNT)
VALUES ('PR-JKL' ,'Boeing 787' ,2017 ,8.0 ,242 ,'Boeing');
INSERT INTO AERONAVES (AERON_PREFX ,AERON_MODELO ,AERON_ANOFABR ,AERON_AUTON ,AERON_CAPAC ,AERON_FABRNT)
VALUES ('PR-MNO' ,'Airbus A350' ,2019 ,9.0 ,300 ,'Airbus');

UPDATE AERONAVES
SET AERON_CAPAC = 200
WHERE AERON_PREFX = 'PR-ABC';

UPDATE AERONAVES
SET AERON_AUTON = 7.0
WHERE AERON_PREFX = 'PR-ABC';

DELETE FROM AERONAVES 
WHERE AERON_PREFX = 'PR-MNO';
INSERT INTO AERONAVES (AERON_PREFX ,AERON_MODELO ,AERON_ANOFABR ,AERON_AUTON ,AERON_CAPAC ,AERON_FABRNT)
VALUES ('PR-MNO' ,'Airbus A350' ,2019 ,9.0 ,300 ,'Airbus');
#####################################################
# | INSERT | UPDATE | DELETE | [TABELA FUNCIONARIOS]
#####################################################
INSERT INTO FUNCIONARIOS (FUNC_ID,FUNC_NOME,FUNC_DATANASC,FUNC_ENDRC,FUNC_CPF,FUNC_FUNCAO)
VALUES (1,'Lucas Almeida','1985-05-15','Rua Z','12345678900','Piloto');
INSERT INTO FUNCIONARIOS (FUNC_ID,FUNC_NOME,FUNC_DATANASC,FUNC_ENDRC,FUNC_CPF,FUNC_FUNCAO)
VALUES (2,'Fernanda Souza','1990-07-20','Rua Y','98765432100','Copiloto');
INSERT INTO FUNCIONARIOS (FUNC_ID,FUNC_NOME,FUNC_DATANASC,FUNC_ENDRC,FUNC_CPF,FUNC_FUNCAO)
VALUES (3,'Carlos Pereira','1982-03-10','Rua X','11223344556','Comissário de Bordo');
INSERT INTO FUNCIONARIOS (FUNC_ID,FUNC_NOME,FUNC_DATANASC,FUNC_ENDRC,FUNC_CPF,FUNC_FUNCAO)
VALUES (4,'Mariana Santos','1995-09-25','Rua W','99887766554','Comissária de Bordo');
INSERT INTO FUNCIONARIOS (FUNC_ID,FUNC_NOME,FUNC_DATANASC,FUNC_ENDRC,FUNC_CPF,FUNC_FUNCAO)
VALUES (5,'João Mendes','1978-11-30','Rua V','77665544332','Mecânico');

UPDATE FUNCIONARIOS
SET FUNC_FUNCAO = 'Piloto Chefe'
WHERE FUNC_ID = 1;

UPDATE FUNCIONARIOS
SET FUNC_ENDRC = 'Rua Nova Z, 999'
WHERE FUNC_ID = 1;

DELETE FROM FUNCIONARIOS 
WHERE FUNC_ID = 5;
INSERT INTO FUNCIONARIOS (FUNC_ID,FUNC_NOME,FUNC_DATANASC,FUNC_ENDRC,FUNC_CPF,FUNC_FUNCAO)
VALUES (5,'João Mendes','1978-11-30','Rua V','77665544332','Mecânico');

#####################################################
# | INSERT | UPDATE | DELETE | [TABELA VOOS]
#####################################################
#INSERT INTO AERONAVES (AERON_PREFX ,AERON_MODELO ,AERON_ANOFABR ,AERON_AUTON ,AERON_CAPAC ,AERON_FABRNT) VALUES ('PR-MNO' ,'Airbus A350' ,2019 ,9.0 ,300 ,'Airbus');
#SELECT * FROM AERONAVES WHERE AERON_PREFX = 'PR-MNO';

INSERT INTO VOOS(VOO_ID ,VOO_DATA ,VOO_HORA ,VOO_AERON ,VOO_AEROP )
VALUES(1 ,'2024-12-01' ,'08:00:00' ,'PR-ABC' ,1);
INSERT INTO VOOS(VOO_ID ,VOO_DATA ,VOO_HORA ,VOO_AERON ,VOO_AEROP )
VALUES(2 ,'2024-12-01' ,'10:30:00' ,'PR-GHI' ,2);
INSERT INTO VOOS(VOO_ID ,VOO_DATA ,VOO_HORA ,VOO_AERON ,VOO_AEROP )
VALUES(3 ,'2024-12-02' ,'14:00:00' ,'PR-JKL' ,3);
INSERT INTO VOOS(VOO_ID ,VOO_DATA ,VOO_HORA ,VOO_AERON ,VOO_AEROP )
VALUES(4 ,'2024-12-02' ,'16:30:00' ,'PR-MNO' ,4);
INSERT INTO VOOS(VOO_ID ,VOO_DATA ,VOO_HORA ,VOO_AERON ,VOO_AEROP )
VALUES(5 ,'2024-12-03' ,'18:45:00' ,'PR-JKL' ,5);

UPDATE VOOS
SET VOO_HORA = '09:00:00'
WHERE VOO_ID = 1;

UPDATE VOOS
SET VOO_DATA = '2024-12-02'
WHERE VOO_ID = 1;

DELETE FROM VOOS 
WHERE VOO_ID = 5;
INSERT INTO VOOS(VOO_ID ,VOO_DATA ,VOO_HORA ,VOO_AERON ,VOO_AEROP )
VALUES(5 ,'2024-12-03' ,'18:45:00' ,'PR-JKL' ,5);
#####################################################
# | INSERT | UPDATE | DELETE | [TABELA RESERVAS]
#####################################################
INSERT INTO RESERVAS (RESERV_COD, RESERV_VOO, RESERV_PASS)
VALUES (1, 1, '123.456.789-00');
INSERT INTO RESERVAS (RESERV_COD, RESERV_VOO, RESERV_PASS)
VALUES (2, 2, '987.654.321-00');
INSERT INTO RESERVAS (RESERV_COD, RESERV_VOO, RESERV_PASS)
VALUES (3, 3, '111.222.333-44');
INSERT INTO RESERVAS (RESERV_COD, RESERV_VOO, RESERV_PASS)
VALUES (4, 4, '555.666.777-88');
INSERT INTO RESERVAS (RESERV_COD, RESERV_VOO, RESERV_PASS)
VALUES (5, 5, '999.888.777-66');

UPDATE RESERVAS
SET RESERV_VOO = 2
WHERE RESERV_COD = 1;

UPDATE RESERVAS
SET RESERV_PASS = '987.654.321-00'
WHERE RESERV_COD = 1;

DELETE FROM RESERVAS 
WHERE RESERV_COD = 5;
INSERT INTO RESERVAS (RESERV_COD, RESERV_VOO, RESERV_PASS)
VALUES (5, 5, '999.888.777-66');
#####################################################
# | INSERT | UPDATE | DELETE | [TABELA VOOS_FUNCIONARIOS]
#####################################################
# Inserindo funcionários em voos específicos
INSERT INTO VOOS_FUNCIONARIOS (VSFN_VOOS, VSFN_FUNCIONARIOS)
VALUES (1, 1);  # Funcionario 1 no voo 1
INSERT INTO VOOS_FUNCIONARIOS (VSFN_VOOS, VSFN_FUNCIONARIOS)
VALUES (1, 2);  # Funcionario 2 no voo 1
INSERT INTO VOOS_FUNCIONARIOS (VSFN_VOOS, VSFN_FUNCIONARIOS)
VALUES (2, 3);  # Funcionario 3 no voo 2
INSERT INTO VOOS_FUNCIONARIOS (VSFN_VOOS, VSFN_FUNCIONARIOS)
VALUES (2, 4);  # Funcionario 4 no voo 2
INSERT INTO VOOS_FUNCIONARIOS (VSFN_VOOS, VSFN_FUNCIONARIOS)
VALUES (3, 5);  # Funcionario 5 no voo 3

# Atualizando o voo do funcionário
UPDATE VOOS_FUNCIONARIOS
SET VSFN_VOOS = 3
WHERE VSFN_VOOS = 1 AND VSFN_FUNCIONARIOS = 2;  # Funcionario 2 movido do Voo 1 para o Voo 3

# Atualizando o funcionário atribuído a um voo
UPDATE VOOS_FUNCIONARIOS
SET VSFN_FUNCIONARIOS = 4
WHERE VSFN_VOOS = 3 AND VSFN_FUNCIONARIOS = 5;  # Alterando o funcionário do Voo 3 para o Funcionario 4

DELETE FROM VOOS_FUNCIONARIOS
WHERE VSFN_VOOS = 2 AND VSFN_FUNCIONARIOS = 3; # Remover o Funcionario 3 do Voo 2