CREATE SCHEMA EC2_CC1M;

USE EC2_CC1M;
# CRIANDO AS TABELAS SEM CHAVES ESTRANGEIRAS
# #######################################################################################
# ##############################| CRIANDO A TABELA PASSAGEIROS |#########################
# #######################################################################################
CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF VARCHAR(14) PRIMARY KEY,
PASS_NOME VARCHAR(50) NOT NULL,
PASS_TEL VARCHAR(15) NOT NULL,
PASS_ENDRC TEXT NOT NULL,
PASS_EMAIL VARCHAR(30) NOT NULL
);
#DAR COMANDOS DE ALTER NA TABELA PASSAGEIROS
ALTER TABLE PASSAGEIROS ADD column DESCRICAO_PASSAGEIROS TEXT NOT NULL;
ALTER TABLE PASSAGEIROS MODIFY COLUMN DESCRICAO_PASSAGEIROS VARCHAR(100);
ALTER TABLE PASSAGEIROS CHANGE COLUMN DESCRICAO_PASSAGEIROS DESCRICAO_PASSAGEIROS1 VARCHAR(100);
ALTER TABLE PASSAGEIROS DROP COLUMN DESCRICAO_PASSAGEIROS1;
# ######################################################################################
# ##############################| CRIANDO A TABELA AEROPORTOS |#########################
# ######################################################################################
CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_COD INT PRIMARY KEY,
AEROP_NOME VARCHAR(20) NOT NULL,
AEROP_CIDADE VARCHAR(20) NOT NULL,
AEROP_PAIS VARCHAR(20) NOT NULL,
AEROP_LAT DECIMAL(2,2) NOT NULL,
AEROP_LONG DECIMAL(3,2) NOT NULL 
);
#DAR COMANDOS DE ALTER NA TABELA AEROPORTOS
ALTER TABLE AEROPORTOS ADD column DESCRICAO_AEROPORTOS TEXT NOT NULL;
ALTER TABLE AEROPORTOS MODIFY COLUMN DESCRICAO_AEROPORTOS VARCHAR(100);
ALTER TABLE AEROPORTOS CHANGE COLUMN DESCRICAO_AEROPORTOS DESCRICAO_AEROPORTOS1 VARCHAR(100);
ALTER TABLE AEROPORTOS DROP COLUMN DESCRICAO_AEROPORTOS1;
# #####################################################################################
# ##############################| CRIANDO A TABELA AERONAVES |#########################
# #####################################################################################
CREATE TABLE IF NOT EXISTS AERONAVES(
AERON_PREFX VARCHAR(10) PRIMARY KEY,
AERON_MODELO VARCHAR(20) NOT NULL,
AERON_ANOFABR INT NOT NULL,
AERON_AUTON DECIMAL(3,2) NOT NULL,
AERON_CAPAC INT NOT NULL,
AERON_FABRNT VARCHAR(20) NOT NULL
);
#DAR COMANDOS DE ALTER NA TABELA AERONAVES
ALTER TABLE AERONAVES ADD column DESCRICAO_AERONAVES TEXT NOT NULL;
ALTER TABLE AERONAVES MODIFY COLUMN DESCRICAO_AERONAVES VARCHAR(100);
ALTER TABLE AERONAVES CHANGE COLUMN DESCRICAO_AERONAVES DESCRICAO_AERONAVES1 VARCHAR(100);
ALTER TABLE AERONAVES DROP COLUMN DESCRICAO_AERONAVES1;
# #####################################################################################
# ##############################| CRIANDO A TABELA FUNCIONARIOS |######################
# #####################################################################################
CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_NOME VARCHAR(40) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_ENDRC TEXT NOT NULL,
FUNC_CPF VARCHAR(14) NOT NULL,
FUNC_FUNCAO TEXT NOT NULL
);
#DAR COMANDOS DE ALTER NA TABELA FUNCIONARIOS
ALTER TABLE FUNCIONARIOS ADD column DESCRI_FUNCIONARIOS TEXT NOT NULL;
ALTER TABLE FUNCIONARIOS MODIFY COLUMN DESCRI_FUNCIONARIOS VARCHAR(100);
ALTER TABLE FUNCIONARIOS CHANGE COLUMN DESCRI_FUNCIONARIOS DESCRI_FUNCIONARIOS1 VARCHAR(100);
ALTER TABLE FUNCIONARIOS DROP COLUMN DESCRI_FUNCIONARIOS1;
# #############################################################################
# ##############################| CRIANDO A TABELA VOOS |######################
# #############################################################################
CREATE TABLE IF NOT EXISTS VOOS(
VOO_ID INT PRIMARY KEY,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AERON VARCHAR(10) NOT NULL,
VOO_AEROP INT NOT NULL,
CONSTRAINT FK_AERONAVES FOREIGN KEY (VOO_AERON) REFERENCES AERONAVES(AERON_PREFX),
CONSTRAINT FK_AEROPORTOS FOREIGN KEY (VOO_AEROP) REFERENCES AEROPORTOS(AEROP_COD)
);
#DAR COMANDOS DE ALTER NA TABELA VOOS
ALTER TABLE VOOS ADD column DESCRICAO_VOOS TEXT NOT NULL;
ALTER TABLE VOOS MODIFY COLUMN DESCRICAO_VOOS VARCHAR(100);
ALTER TABLE VOOS CHANGE COLUMN DESCRICAO_VOOS DESCRICAO_VOOS1 VARCHAR(100);
ALTER TABLE VOOS DROP COLUMN DESCRICAO_VOOS1;
# #################################################################################
# ##############################| CRIANDO A TABELA RESERVAS |######################
# #################################################################################
CREATE TABLE IF NOT EXISTS RESERVAS(
RESERV_COD INT PRIMARY KEY,
RESERV_VOO INT NOT NULL,
RESERV_PASS VARCHAR(14) NOT NULL,
CONSTRAINT FK_VOOS FOREIGN KEY (RESERV_VOO) REFERENCES VOOS(VOO_ID),
CONSTRAINT FK_PASSAGEIROS FOREIGN KEY (RESERV_PASS) REFERENCES PASSAGEIROS(PASS_CPF)
);
#DAR COMANDOS DE ALTER NA TABELA RESERVAS
ALTER TABLE RESERVAS ADD column DESCRI_RESERVAS TEXT NOT NULL;
ALTER TABLE RESERVAS MODIFY COLUMN DESCRI_RESERVAS VARCHAR(100);
ALTER TABLE RESERVAS CHANGE COLUMN DESCRI_RESERVAS DESCRI_RESERVAS1 VARCHAR(100);
ALTER TABLE RESERVAS DROP COLUMN DESCRI_RESERVAS1;
# #################################################################################
# ##############################| CRIANDO A TABELA VOOS_FUNCIONARIOS |#############
# #################################################################################
CREATE TABLE IF NOT EXISTS VOOS_FUNCIONARIOS(
VSFN_VOOS INT,
VSFN_FUNCIONARIOS INT,
PRIMARY KEY(VSFN_VOOS,VSFN_FUNCIONARIOS),
CONSTRAINT VSFN_FK_VOOS FOREIGN KEY (VSFN_VOOS) REFERENCES VOOS(VOO_ID),
CONSTRAINT VSFN_FK_FUNCIONARIOS FOREIGN KEY (VSFN_FUNCIONARIOS) REFERENCES FUNCIONARIOS(FUNC_ID)
);
#DAR COMANDOS DE ALTER NA TABELA VOOS_FUNCIONARIOS
ALTER TABLE VOOS_FUNCIONARIOS ADD column DESCR_VOOS_FUNCIONARIOS TEXT NOT NULL;
ALTER TABLE VOOS_FUNCIONARIOS MODIFY COLUMN DESCR_VOOS_FUNCIONARIOS VARCHAR(100);
ALTER TABLE VOOS_FUNCIONARIOS CHANGE COLUMN DESCR_VOOS_FUNCIONARIOS DESCR_VOOS_FUNCIONARIOS VARCHAR(100);
ALTER TABLE VOOS_FUNCIONARIOS DROP COLUMN DESCR_VOOS_FUNCIONARIOS;
# #################################################################################
#MOSTRANDO TABELAS
show tables;
#DROPANDO BASE DE DADOS :D
drop schema EC2_CC1M; #DROP SCHEMA
